apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitlab.fullname" . }}
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
{{- end }}

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: gitlab-root
  namespace: default
stringData:
  initial_root_password: {{ .Values.initialRootPassword }}