apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "groups-ui.fullname" . }}
  labels:
    {{- include "groups-ui.labels" . | nindent 4 }}

data:
  settings.json: |
{{ .Values.settings | indent 4 }}

  customize.sh: |
    #!/bin/sh
    index=/var/www/index.html

{{- if .Values.openGraph }}
    meta={{ .Values.openGraph }}
    sed -i "s,</head>,${meta}," $index

    cat <<EOF > /tmp/og
{{ .Values.openGraph | indent 4 }}
    EOF
{{- end}}

{{- if .Values.faviconsUrl }}
    curl -o /tmp/favicons.tgz {{ .Values.faviconsUrl }}
    tar xzf /tmp/favicons.tgz -C /var/www
    meta=$(cat /var/www/favicon.html)
    if [ -n "$meta" ]; then
      sed -i "s,</head>,${meta}," $index
    fi
{{- end}}

{{- if .Values.basehref }}
    basehref={{ .Values.basehref }}
    sed -i "s,base\ href=\"/\",base\ href=\"$basehref\"," $index
    ln -s /var/www /var/www${basehref}
{{- end}}
