apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gallery-api.fullname" . }}
  labels:
    {{- include "gallery-api.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "gallery-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gallery-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gallery-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- include "gallery-api.env" . | nindent 10 }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{- toYaml .Values.command | nindent 10 }}
          {{- if .Values.certificateMap }}
          env:
            - name: SSL_CERT_DIR
              value: /usr/local/share/ca-certificates/
          {{- end }}
          ports:
            - name: http
              containerPort: {{ default 8080 .Values.service.targetPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.certificateMap }}
          volumeMounts:
            - mountPath: /usr/local/share/ca-certificates
              name: certificates
          {{- end }}
      {{- if .Values.certificateMap }}
      volumes:
        - name: certificates
          configMap:
            name: {{ .Values.certificateMap }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
