apiVersion: v1
kind: Service
metadata:
  name: roundcubemail
  labels:
    service: roundcubemail
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    service: roundcubemail