{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "identity-api.serviceAccountName" . }}
  labels:
    {{- include "identity-api.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "identity-api.serviceAccountName" . }}
  labels:
    {{- include "identity-api.labels" . | nindent 4 }}
  
rules:
  - apiGroups:
      - 'batch'
    resources:
      - jobs
    verbs:
      - get
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "identity-api.serviceAccountName" . }}
  labels:
    {{- include "identity-api.labels" . | nindent 4 }}
  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "identity-api.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "identity-api.serviceAccountName" . }}
{{- end }}
