apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mkdocs-material.fullname" . }}
  labels:
    {{- include "mkdocs-material.labels" . | nindent 4 }}

data:
  {{- if not .Values.giturl }}
  mkdocs.yml: |-
    {{- tpl (toYaml .Values.mkdocs) . | nindent 4 }}
  {{- end }}

  nginx.conf: |-
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        location / {
            root   /mkdocs/docs/site;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
