apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mkdocs-material.fullname" . }}
  labels:
    {{- include "mkdocs-material.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mkdocs-material.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mkdocs-material.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mkdocs-material.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- if .Values.giturl }}
        - name: git-pull
          image: "bitnami/git"
          command: ["/entry.d/git-pull.sh"]
          env:
            - name: DOCS_GIT_URL
              value: {{ .Values.giturl }}
            - name: DOCS_GIT_BRANCH
              value: {{ .Values.gitbranch }}
            {{- if .Values.gitCredentialsSecret }}
            - name: DOCS_GIT_CRED_FILE
              value: {{ default ".git-credentials" .Values.gitCredentialsSecretKey }}
            {{- end }}
            {{- if .Values.gitPath }}
            - name: DOCS_GIT_PATH
              value: {{ .Values.gitPath | trimPrefix "/" }}
            {{- end }}
            {{- if .Values.mkdocs.site_url }}
            - name: DOCS_SITE_URL
              value: {{ .Values.mkdocs.site_url }}
            {{- end }}
          volumeMounts:
            - mountPath: /entry.d
              name: {{ include "mkdocs-material.fullname" . }}-entry
            - mountPath: /docs
              name: {{ include "mkdocs-material.fullname" . }}-vol
              subPath: {{ include "mkdocs-material.subpathPrefix" . }}docs
            - mountPath: /git
              name: {{ include "mkdocs-material.fullname" . }}-vol
              subPath: {{ include "mkdocs-material.subpathPrefix" . }}git
            {{- if .Values.gitCredentialsSecret }}
            - mountPath: /git-credentials
              name: {{ include "mkdocs-material.fullname" . }}-git-creds
            {{- end }}
            {{- if or .Values.certificateMap .Values.cacert }}
            - mountPath: /usr/local/share/ca-certificates
              name: certificates
            {{- end }}
        {{- end }}
        - name: mkdocs-build
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
            {{- if .Values.giturl }}
          command: ["/entry.d/mkdocs-build.sh"]
          {{- if .Values.gitPath }}
          env:
            - name: DOCS_GIT_PATH
              value: {{ .Values.gitPath | trimPrefix "/" }}
          {{- end }}
          volumeMounts:
            - mountPath: /entry.d
              name: {{ include "mkdocs-material.fullname" . }}-entry
            - mountPath: /docs
              name: {{ include "mkdocs-material.fullname" . }}-vol
              subPath: {{ include "mkdocs-material.subpathPrefix" . }}docs
            - mountPath: /git
              name: {{ include "mkdocs-material.fullname" . }}-vol
              subPath: {{ include "mkdocs-material.subpathPrefix" . }}git
            {{- else }}
          args: ["build"]
          volumeMounts:
            - mountPath: /docs/mkdocs.yml
              name: {{ include "mkdocs-material.fullname" . }}
              subPath: mkdocs.yml
            - mountPath: /docs/docs
              name: {{ include "mkdocs-material.fullname" . }}-files
            - mountPath: /docs/site
              name: {{ include "mkdocs-material.fullname" . }}-vol
              subPath: {{ include "mkdocs-material.subpathPrefix" . }}docs/site
            {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: nginx:alpine
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: {{ include "mkdocs-material.fullname" . }}
              subPath: nginx.conf
            - mountPath: /mkdocs
              name: {{ include "mkdocs-material.fullname" . }}-vol
              {{- if include "mkdocs-material.subpathPrefix" . }}
              subPath: {{ include "mkdocs-material.subpathPrefix" . | trimSuffix "/" }}
              {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: {{ include "mkdocs-material.fullname" . }}
        configMap:
          name: {{ include "mkdocs-material.fullname" . }}
      {{- if .Values.giturl }}
      - name: {{ include "mkdocs-material.fullname" . }}-entry
        configMap:
          name: {{ include "mkdocs-material.fullname" . }}-entry
          defaultMode: 0775
      {{- if .Values.gitCredentialsSecret }}
      - name: {{ include "mkdocs-material.fullname" . }}-git-creds
        secret:
          secretName: {{ .Values.gitCredentialsSecret }}
          defaultMode: 0600
      {{- end }}
      {{- else }}
      - name: {{ include "mkdocs-material.fullname" . }}-files
        configMap:
          name: {{ include "mkdocs-material.fullname" . }}-files
      {{- end }}
      {{- if .Values.storage.existing }}
      - name: {{ include "mkdocs-material.fullname" . }}-vol
        persistentVolumeClaim:
          claimName: {{ .Values.storage.existing }}
      {{- else if .Values.storage.size }}
      - name: {{ include "mkdocs-material.fullname" . }}-vol
        persistentVolumeClaim:
          claimName: {{ include "mkdocs-material.fullname" . }}
      {{- else if .Values.giturl }}
      {{- fail "Git deployment mode requires persistent volume" }}
      {{- else }}
      - name: {{ include "mkdocs-material.fullname" . }}-vol
        emptyDir: {}
      {{- end }}
      {{- if .Values.certificateMap }}
      - name: certificates
        configMap:
          name: {{ .Values.certificateMap }}
      {{- end }}
      {{- if .Values.cacert }}
      - name: certificates
        configMap:
          name: {{ include "mkdocs-material.fullname" . }}-cacerts
      {{- end }}
