{{- $fullName := include "steamfitter-ui.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "steamfitter-ui.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "steamfitter-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "steamfitter-ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "steamfitter-ui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "steamfitter-api.fullname" . }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /usr/share/nginx/html/assets/config/settings.env.json
              subPath: settings.env.json
              name: {{ $fullName }}-settings
      {{ if eq .Values.identity.register true }}
      initContainers:
        - name: identity-seed
          image: dwdraju/alpine-curl-jq
          {{ if .Values.identity.initCommand }}
          command: {{- toYaml .Values.identity.initCommand | nindent 10 }}
          {{ else }}
          command: ['/seed/seed.sh', {{ .Chart.Name }}, "/seed"]
          {{- end }}
          volumeMounts:
          - name: {{ .Chart.Name }}-identity-seed
            mountPath: /seed
      {{- end }}
      volumes:
        - name: {{ $fullName }}-settings
          configMap:
            name: {{ $fullName }}
        {{ if eq .Values.identity.register true }}
        - name: {{ .Chart.Name }}-identity-seed
          projected:
            sources:
            - configMap:
                name: {{ $fullName  }}-seed
            - configMap:
                name: {{ .Values.identity.identityMap }}
                items:
                  - key: seed.sh
                    path: seed.sh
                    mode: 0777
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
