apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gameboard-ui.fullname" . }}
  labels:
    {{- include "gameboard-ui.labels" . | nindent 4 }}

data:
  settings.json: |-
{{ .Values.settings | indent 4 }}

  customize.sh: |
    src=/var/www
{{- if .Values.basehref }}
    basehref=`echo -n {{ .Values.basehref | quote }} | sed -e s,^/,, -e s,/$,,`
    if [ -n "$basehref" ]; then
      find $src/* -name index.html -exec \
        sed -i "s,base\ href=\"\(.*\)\",base\ href=\"/$basehref\1\"," {} \;
      dst=$src/$basehref
      mkdir -p `dirname $dst`
      ln -s $src $dst
    fi
{{- end }}

{{- if .Values.openGraph }}
    meta=$(echo -n {{ .Values.openGraph | quote }} | sed -e 's/[/\&]/\\&/g')
    sed -i.bak -e "s/<\/head>/${meta}\n<\/head>/" $src/index.html
{{- end}}

{{- if .Values.faviconsUrl }}
    curl -o /tmp/favicons.tgz {{ .Values.faviconsUrl | quote }}
    tar xzf /tmp/favicons.tgz -C /var/www
    meta=$(cat /var/www/favicon.html | sed -e 's/[/\&]/\\&/g')
    sed -i.bak -e "s/<\/head>/${meta}\n<\/head>/" $src/index.html
{{- end}}
