# Default values for learninglocker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
learninglocker-ui:
  image:
    repository: fundocker/learninglocker
    tag: v6.1.1
    pullPolicy: IfNotPresent

  storage:
    existing: ""

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: learninglocker.example.com
        paths:
        - /
    tls:
      - secretName: ""
        hosts:
         - example.com

  env:
    NODE_ENV: production
    SITE_URL: localhost
    UI_PORT: 3000
    API_PORT: 8080
    APP_SECRET: ""
    REDIS_HOST: redis
    REDIS_PORT: 6379
    REDIS_DB: 0
    REDIS_PREFIX: learninglocker
    LOG_MIN_LEVEL: info
    WINSTON_CLOUDWATCH_ENABLED: false
    SMTP_HOST: ""
    SMTP_PORT: ""
    SMTP_SECURED: ""
    SMTP_USER: ""
    SMTP_PASS: ""
    QUEUE_PROVIDER: REDIS
    MONGODB_PATH: mongodb://mongodb:27017/learninglocker_v2

learninglocker-api:
  image:
    repository: fundocker/learninglocker
    tag: v6.1.1
    pullPolicy: IfNotPresent

  storage:
    existing: ""

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    hosts:
      - host: learninglocker.example.com
        paths:
        - /api/?(.*)
    tls:
      - secretName: ""
        hosts:
         - example.com

  env:
    NODE_ENV: production
    SITE_URL: localhost
    UI_PORT: 3000
    API_PORT: 8080
    APP_SECRET: ""
    REDIS_HOST: redis
    REDIS_PORT: 6379
    REDIS_DB: 0
    REDIS_PREFIX: learninglocker
    LOG_MIN_LEVEL: info
    WINSTON_CLOUDWATCH_ENABLED: false
    SMTP_HOST: ""
    SMTP_PORT: ""
    SMTP_SECURED: ""
    SMTP_USER: ""
    SMTP_PASS: ""
    QUEUE_PROVIDER: REDIS
    MONGODB_PATH: mongodb://mongodb:27017/learninglocker_v2

learninglocker-worker:
  image:
    repository: fundocker/learninglocker
    tag: v6.1.1
    pullPolicy: IfNotPresent

  storage:
    existing: ""

  siteadmin:
    organization: "default"
    email: "administrator@this.ws"
    password: ""  

  env:
    NODE_ENV: production
    SITE_URL: localhost
    UI_PORT: 3000
    API_PORT: 8080
    APP_SECRET: ""
    REDIS_HOST: redis
    REDIS_PORT: 6379
    REDIS_DB: 0
    REDIS_PREFIX: learninglocker
    LOG_MIN_LEVEL: info
    WINSTON_CLOUDWATCH_ENABLED: false
    SMTP_HOST: ""
    SMTP_PORT: ""
    SMTP_SECURED: ""
    SMTP_USER: ""
    SMTP_PASS: ""
    QUEUE_PROVIDER: REDIS
    MONGODB_PATH: mongodb://mongodb:27017/learninglocker_v2

learninglocker-xapi:
  image:
    repository: fundocker/xapi-service
    tag: v3.6.1
    pullPolicy: IfNotPresent

  storage:
    existing: ""

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: learninglocker.example.com
        paths:
        - /data
    tls:
      - secretName: ""
        hosts:
         - example.com

  env:
    REDIS_URL: redis://redis:6379/0
    REDIS_PREFIX: learninglocker
    WINSTON_CLOUDWATCH_ENABLED: false
    MONGODB_PATH: mongodb://mongodb:27017/learninglocker_v2
    FS_REPO: local