apiVersion: v2
name: console-ui
description: UI for interacting with VMWare consoles from Player
type: application
version: 1.3.0
appVersion: 3.1.1
home: https://cmu-sei.github.io/crucible
sources:
  - https://github.com/cmu-sei/helm-charts/tree/main/charts/player/charts/console-ui
dependencies:
- name: crucible-common
  version: 1.x.x
  repository: https://helm.cmusei.dev/charts
