image:
  pullPolicy: IfNotPresent

# Ingress configuration example for NGINX
# TLS and Host URLs need configured
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  tls:
    - secretName: ""
      hosts:
        - example.com

st2web:
  service:
    hostname: stackstorm.example.com

enterprise:
  enabled: false

mongodb-ha:
  enabled: true
  image:
    # StackStorm currently supports maximum MongoDB v4.0
  serviceAccount: stackstorm-mongodb-ha
  auth:
    enabled: true
    adminUser: "mongo"
    adminPassword: "dzG#yHaZ7!4K3wQbb8pa"
    # Minimal key length is 6 symbols
    key: "82PitDKnti5RngOa7UqbnTTc6bQUwy"
  persistentVolume:
    # This example uses https://github.com/helm/charts/tree/master/stable/nfs-client-provisioner 
    # as a PV provisioner, and is named "nfs-client"
    storageClass: nfs-client

rabbitmq-ha:
  enabled: true
  rabbitmqUsername: admin
  # TODO: Use default random 24 character password, but need to fetch this string for use by downstream services
  rabbitmqPassword: "DzGyHbZ7h3KqwGb08pkaLj7"
  persistentVolume:
    enabled: true
    # This example uses https://github.com/helm/charts/tree/master/stable/nfs-client-provisioner 
    # as a PV provisioner, and is named "nfs-client"
    storageClass: nfs-client


st2:
  packs:
    configs:
      # This is the REQUIRED configuration for the vSphere pack
      #
      # Note that ssl_verify is false at the moment due to lack of a mechanism
      # to trust self-signed certificates.  If your vCenter certificate is not self-signed, this can be set to true
      #
      # user and passwd are credentials for a vCenter account that has elevated permissions
      vsphere.yaml: |
        ssl_verify: false
        vsphere:
          default:
            host: vcenter.example.com
            passwd: 
            port: 443
            user: 

    # StackStorm HA mounts non-core packs via a sidecar installation
    # This image is custom-built to contain the vSphere Pack
    # NOTE:  The tag version represents the vSphere Pack version number
    # NOTE:  StackStorm v3.1.0 and under were on Python2, later versions move to Python3,
    #        so the convention used here will assume Python3 unless noted in the tag
    image:
      repository: cmusei
      name: st2packs
      tag: 0.15.1-python2
      pullPolicy: Always

    # Provide a default name for the sensor
    sensors:
      - name: stackstorm-sensor
        serviceAccount:
          attach: false

secrets:
  st2:
    # Username, used to login to StackStorm system
    username: st2admin
    # Password, used to login to StackStorm system
    password: "kZ3vDSk64bmW&#OwD7n&"