---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "caster-api.fullname" . }}-terraform-installation
data:
  install-terraform.sh: |-
{{- include "terraform-installation" . | nindent 4 }}