apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cite-api.fullname" . }}
  labels:
    {{- include "cite-api.labels" . | nindent 4 }}

data:
  seed.json: |-
{{ .Values.conf.seed | indent 4 }}