{{ if eq .Values.kind "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "player-api.fullname" . }}
  labels:
    {{- include "player-api.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "player-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "player-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "player-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- if .Values.existingSecret }}
          envFrom:
            - secretRef:
                name: {{ include "player-api.fullname" . }}
            - secretRef:
                name: {{ (tpl .Values.existingSecret .) }}
          {{- else }}
          envFrom:
            - secretRef:
                name: {{ include "player-api.fullname" . }}
          {{- end }}
          command: {{- toYaml .Values.command | nindent 10 }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
        {{- if .Values.probes.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /api/health/live
              port: http
            initialDelaySeconds: {{ .Values.probes.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.probes.livenessProbe.successThreshold }}
        {{- end }}
        {{- if .Values.probes.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /api/health/ready
              port: http
            initialDelaySeconds: {{ .Values.probes.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.probes.readinessProbe.successThreshold }}
        {{- end }}
        {{- if .Values.probes.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: /api/health/live
              port: http
            initialDelaySeconds: {{ .Values.probes.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.startupProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.startupProbe.failureThreshold }}
            successThreshold: {{ .Values.probes.startupProbe.successThreshold }}
        {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{ if .Values.certificateMap }}
            - mountPath: /usr/local/share/ca-certificates
              name: certificates
            {{- end }}
            - mountPath: /fileupload
              name: {{ include "player-api.fullname" . }}-vol
              subPath: {{ include "player-api.fullname" . }}/fileuploads          
      volumes:
        {{ if .Values.certificateMap }}
        - name: certificates
          configMap:
            name: {{ .Values.certificateMap }}
        {{- end }}
        {{- if .Values.storage.existing }}
        - name: {{ include "player-api.fullname" . }}-vol
          persistentVolumeClaim:
            claimName: {{ .Values.storage.existing }}
        {{- else if .Values.storage.size }}
        - name: {{ include "player-api.fullname" . }}-vol
          persistentVolumeClaim:
            claimName: {{ include "player-api.name" . }}
        {{- else }}
        - name: {{ include "player-api.fullname" . }}-vol
          emptyDir: {}
        {{- end }}      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
