{{- $appName := include "learninglocker.name" . -}}
{{- $appFullName := include "learninglocker.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $appFullName }}-env
  labels:
    app: {{ $appName }}
    chart: {{ include "learninglocker.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
{{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
  MONGO_URL: {{ .Values.env.MONGODB_PATH | quote }}
  STORAGE_REPO: {{ .Values.env.FS_REPO | quote }}
