apiVersion: v2
name: blueprint-api
description: RESTful API for Blueprints
type: application
version: 1.4.0
appVersion: "0.3.10"
home: https://cmu-sei.github.io/crucible
sources:
  - https://github.com/cmu-sei/helm-charts/tree/main/charts/blueprint/charts/blueprint-api
dependencies:
  - name: crucible-common
    version: 1.x.x
    repository: https://helm.cmusei.dev/charts
