apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ui.fullname" . }}
  labels:
    {{- include "ui.labels" . | nindent 4 }}

data:
  settings.json: |
{{ .Values.settings | indent 4 }}

  customize.sh: |
    #!/bin/sh
    index=/var/www/index.html

{{- if .Values.openGraph }}
    meta={{ .Values.openGraph }}
    sed -i "s,</head>,${meta}," $index

    cat <<EOF > /tmp/og
{{ .Values.openGraph | indent 4 }}
    EOF
{{- end}}

{{- if .Values.faviconsUrl }}
    curl -o /tmp/favicons.tgz {{ .Values.faviconsUrl }}
    tar xzf /tmp/favicons.tgz -C /var/www
    meta=$(cat /var/www/favicon.html)
    if [ -n "$meta" ]; then
      sed -i "s,</head>,${meta}," $index
    fi
{{- end}}

{{- if .Values.basehref }}
    src=/var/www
    basehref=`echo $APP_BASEHREF | sed -e s,^/,, -e s,/$,,`
    if [ -n "$basehref" ]; then
      sed -i "s,base\ href=\"/\",base\ href=\"/$basehref/\"," $src/index.html
      dst=$src/$basehref
      mkdir -p `dirname $dst`
      ln -s $src $dst
    fi
{{- end}}
