{{- if and .Values.seedData .Values.macrosPlugin.extraYamlConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "topomojo-api.seedSecret" . }}
  labels:
    {{- include "topomojo-api.labels" . | nindent 4 }}
type: Opaque
data:
{{- $configContent := toYaml .Values.seedData.values }}
  seed-data: |-
    {{- (tpl $configContent $) | nindent 4}}
