{{- if and .Values.seedData .Values.seedData.values (not .Values.seedData.existingSeedDataSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "topomojo-api.seedSecret" . }}
  labels:
    {{- include "topomojo-api.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- $configContent := toYaml .Values.seedData.values }}
  seedData: |-
    {{- (tpl $configContent $) | fromYaml | toPrettyJson | nindent 4 }}
{{- end }}
