---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "caster-api.fullname" . }}-scripts
data:
  install-terraform.sh: |-
{{- include "terraform-installation" . | nindent 4 }}
  vol-permissions.sh: |-
{{- include "vol-permissions" . | nindent 4 }}