apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gameboard-api.fullname" . }}
  labels:
    {{- include "gameboard-api.labels" . | nindent 4 }}

data:
  appsettings.json: |
{{ .Values.settings | indent 4 }}
