apiVersion: v2
name: steamfitter
description: Steamfitter enables the organization and execution of scenario tasks
  on virtual machines via Player VM API (vSphere), SSH, and SMTP.
type: application
version: 1.8.2
home: https://cmu-sei.github.io/crucible/steamfitter
sources:
- https://github.com/cmu-sei/steamfitter.api
- https://github.com/cmu-sei/steamfitter.ui
