identity-api:

  replicaCount: 1

  image:
    tag: ""

  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths: []
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  ## persistence; set existing pvc or size of new pvc
  storage:
    existing: ""
    size: ""
    mode: ReadWriteOnce
    class: default

  # Config app settings with environment vars.
  # Those most likely needing values are listed. For others,
  # see https://github.com/cmu-sei/Identity/blob/master/src/IdentityServer/appsettings.conf
  env:
    # Supported providers: InMemory, PostgreSQL, SqlServer
    Database__Provider: InMemory
    Database__ConnectionString: identity_db
    Branding__ApplicationName: Identity
    Branding__UiHost: /ui
    Cache__Key: idsrv
    Cache__RedisUrl: ""
    Cache__SharedFolder: ""
    Logging__Console__DisableColors: true
    Account__AdminEmail: ""
    Account__AdminPassword: ""
    Account__OverrideCode: ""
    Account__Authentication__SigningCertificate: conf/signer.pfx
    Account__Authentication__SigningCertificatePassword: ""
    Account__Authentication__NoticeFile: "conf/notice.html"
    AppMail__Url: ""
    AppMail__Key: ""
    AppMail__From: ""
    Headers__Cors__Origins__0: ""
    Headers__Cors__Methods__0: ""
    Headers__Cors__Headers__0: ""
    Headers__Cors__AllowCredentials: false
    Headers__Forwarding__TargetHeaders: None

  conf:
    issuers: ""
    notice: ""
    terms: ""
    trouble: ""
    seed: ""
    signer: ""

identity-ui:

  replicaCount: 1

  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths: []
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources: {}
    # limits:
    #   cpu: 50m
    #   memory: 50Mi
    # requests:
    #   cpu: 50m
    #   memory: 50Mi
  ## basehref is the path to the app; if serving the app as a virtual folder,
  
  ## add the path here.
  # basehref: /ui
  basehref: ""

  ## settings is stringified json that gets included as assets/settings.json
  settings: "{}"
