apiVersion: apps/v1
kind: Deployment
metadata:
  name: dovecot
  labels:
    service: dovecot
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      service: dovecot
  template:
    metadata:
      labels:
        service: dovecot
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - env:
        securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: dovecot
        ports:
        - containerPort: 143
          name: imap
        - containerPort: 24
          name: lmtp
        - containerPort: 12345
          name: auth
        - containerPort: 22
          name: ssh
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - mountPath: /etc/dovecot
          name: dovecot
          subPath: dovecot-conf
        - mountPath: /srv/mail
          name: dovecot-data
          subPath: maildir
      restartPolicy: Always
      volumes:
      {{- range .Values.volumes }}
      - name: {{ .name }}
        persistentVolumeClaim:
          claimName: {{ .persistentVolumeClaim.claimName}}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}