apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blueprint-ui.fullname" . }}
  labels:
    {{- include "blueprint-ui.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $val := .Values.env }}
  {{ $key }}: {{ (tpl ($val | toString) $) | quote }}
{{- end }}