{{- if .Values.st2web.config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-st2web-config
  annotations:
    description: Custom StackStorm Web config which will override defaults
  labels: {{- include "stackstorm-ha.labels" (list $ "st2") | nindent 4 }}
data:
  # User-defined st2web config with custom settings to replace default config.js
  # See https://github.com/StackStorm/st2web#connecting-to-st2-server for more info
  st2web.config.js: |
{{ .Values.st2web.config | indent 4 }}
{{- end }}
