{{- if .Values.st2.rbac.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-st2-rbac-roles
  annotations:
    description: Custom StackStorm RBAC roles, shipped in '/opt/stackstorm/rbac/roles/'
  labels: {{- include "stackstorm-ha.labels" (list $ "st2") | nindent 4 }}
data:
{{- range $filename, $contents := .Values.st2.rbac.roles }}
  {{/* to support removing default files, skip files with empty contents */}}
  {{- if $contents }}
  {{ $filename }}: |
    {{- $contents | nindent 4 }}
  {{- end }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-st2-rbac-assignments
  annotations:
    description: Custom StackStorm RBAC role assignments, shipped in '/opt/stackstorm/rbac/assignments/'
  labels: {{- include "stackstorm-ha.labels" (list $ "st2") | nindent 4 }}
data:
{{- range $filename, $contents := .Values.st2.rbac.assignments }}
  {{/* to support removing default files, skip files with empty contents */}}
  {{- if $contents }}
  {{ $filename }}: |
    {{- $contents | nindent 4 }}
  {{- end }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-st2-rbac-mappings
  annotations:
    description: StackStorm RBAC LDAP groups-to-roles mapping rules, shipped in '/opt/stackstorm/rbac/mappings/'
  labels: {{- include "stackstorm-ha.labels" (list $ "st2") | nindent 4 }}
data:
{{- if .Values.st2.rbac.mappings }}
{{ toYaml .Values.st2.rbac.mappings | indent 2 }}
{{ else }}
  {}
{{ end }}
{{- end }}
