---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-st2-urls
  annotations:
    description: StackStorm service URLs, used across entire st2 cluster
  labels: {{- include "stackstorm-ha.labels" (list $ "st2") | nindent 4 }}
data:
  ST2_AUTH_URL: http://{{ .Release.Name }}-st2auth:9100/
  ST2_API_URL: http://{{ .Release.Name }}-st2api:9101/
  ST2_STREAM_URL: http://{{ .Release.Name }}-st2stream:9102/
