{{- if .Values.st2.overrides }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-st2-overrides-configs
  annotations:
    description: StackStorm override configs defined in helm values, shipped in (or copied to) '/opt/stackstorm/overrides'
  labels: {{- include "stackstorm-ha.labels" (list $ "st2") | nindent 4 }}
data:
{{ toYaml .Values.st2.overrides | indent 2 }}
{{- end }}
