# Notify users about breaking change regarding secrets, to not destroy current installations
{{- $deprecated_ssh_key := (default (dict) (default (dict) .Values.secrets).st2).ssh_key }}
{{- if $deprecated_ssh_key }}
{{- fail "Please update your values! The ssh_key value moved from secrets.st2.* to st2.*" }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  {{- $name := print .Release.Name "-st2-ssh" }}
  name: {{ $name }}
  annotations:
    description: StackStorm SSH secret key for 'stanley' user, used to run actions on remote machines
  labels: {{- include "stackstorm-ha.labels" (list $ "st2") | nindent 4 }}
type: Opaque
data:
  # SSH private key for the 'stanley' system user ('system_user.ssh_key_file' in st2.conf).
{{- $previous := lookup "v1" "Secret" .Release.Namespace $name }}
{{- if and $previous (not .Values.st2.ssh_key) }}
  private_key: {{ $previous.data.private_key }}
{{ else }}
  private_key: {{ default (genPrivateKey "rsa") .Values.st2.ssh_key | b64enc | quote }}
{{ end }}
