{{ if .Values.st2chatops.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-st2chatops
  annotations:
    description: Custom StackStorm chatops config, passed to hubot as ENV vars
  labels: {{- include "stackstorm-ha.labels" (list $ "st2chatops") | nindent 4 }}
type: Opaque
data:
{{- range $env, $value := .Values.st2chatops.env }}
  {{ $env }}: {{ tpl ($value | toString) $ | b64enc | quote }}
{{- end }}
{{- end }}
