---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-st2-kv
  annotations:
    description: Key/Value pairs to save in StackStorm's datastore
  labels: {{- include "stackstorm-ha.labels" (list $ "st2") | nindent 4 }}
type: Opaque
data:
  st2kv.yaml: {{ tpl (toYaml .Values.st2.keyvalue ) . | b64enc | quote }}
