# Notify users about breaking change regarding secrets, to not destroy current installations
{{- $deprecated_crypto_key := (default (dict) (default (dict) .Values.secrets).st2).datastore_crypto_key }}
{{- if $deprecated_crypto_key }}
{{- fail "Please update your values! The datastore_crypto_key value moved from secrets.st2.* to st2.*" }}
{{- else if and (ne "disable" (default "" .Values.st2.datastore_crypto_key)) (not .Values.st2.existingDatastoreSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  {{- $name := print .Release.Name "-st2-datastore-crypto-key" }}
  name: {{ $name }}
  annotations:
    description: StackStorm crypto key used to encrypt/decrypt KV records
  labels: {{- include "stackstorm-ha.labels" (list $ "st2") | nindent 4 }}
type: Opaque
data:
  # Datastore key used to encrypt/decrypt record for the KV store
{{- $previous := lookup "v1" "Secret" .Release.Namespace $name }}
{{- if .Values.st2.datastore_crypto_key }}
  datastore_crypto_key: {{ .Values.st2.datastore_crypto_key | b64enc }}
{{- else if $previous }}
  datastore_crypto_key: {{ $previous.data.datastore_crypto_key }}
{{- else }}
  datastore_crypto_key: {{ tpl (.Files.Get "conf/datastore_crypto_key.yaml") . | fromYaml | toRawJson | b64enc }}
{{- end }}

{{- end }}
