{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "stackstorm-ha.serviceAccountName" . }}
  {{- if .Values.serviceAccount.serviceAccountAnnotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.serviceAccountAnnotations | nindent 4 }}
  {{- end }}
  labels: {{- include "stackstorm-ha.labels" (list $ (include "stackstorm-ha.name" $)) | nindent 4 }}
    {{- if .Values.serviceAccount.serviceAccountLabels }}
    {{- toYaml .Values.serviceAccount.serviceAccountLabels | nindent 4 }}
    {{- end }}
  {{- if .Values.serviceAccount.pullSecret }}
imagePullSecrets:
- name: "{{ .Values.serviceAccount.pullSecret }}"
  {{- end }}
{{- end }}
