{{- if .Values.consoleIngress.enabled }}
{{- $apiVersion := include "common.ingress.apiVersion" (dict "ingress" .Values.consoleIngress "context" $) }}
{{/* Not using common.names.fullname for fullName, as that would deploy as the same name/backend target as the vm-api */}}
{{- $name := default "player-console" .Values.consoleIngress.name }}
{{- $fullName :=  printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- $svcPort := .Values.service.port }}
{{- include "common.ingress.template" (dict "rootContext" $ "localContext" . "ingress" .Values.consoleIngress "fullName" $fullName "svcPort" $svcPort) }}
{{- end }}
