apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vm-api.fullname" . }}
  labels:
    {{- include "vm-api.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "vm-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "vm-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vm-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          envFrom:
            - secretRef:
                name: {{ include "vm-api.fullname" . }}
          command: {{- toYaml .Values.command | nindent 10 }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health/live
              port: http
          readinessProbe:
            httpGet:
              path: /api/health/ready
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{ if .Values.certificateMap }}
          volumeMounts:
            - mountPath: /usr/local/share/ca-certificates
              name: certificates
          {{- end }}
      {{ if eq .Values.identity.register true }}
      initContainers:
        - name: identity-seed
          image: dwdraju/alpine-curl-jq
          {{ if .Values.identity.initCommand }}
          command: {{- toYaml .Values.identity.initCommand | nindent 10 }}
          {{ else }}
          command: ['/seed/seed.sh', {{ .Chart.Name }}, "/seed"]
          {{- end }}
          volumeMounts:
          - name: {{ .Chart.Name }}-identity-seed
            mountPath: /seed
      {{- end }}
          
      volumes:
      {{ if .Values.certificateMap }}
        - name: certificates
          configMap:
            name: {{ .Values.certificateMap }}
      {{- end }}
      {{ if eq .Values.identity.register true }}
        - name: {{ .Chart.Name }}-identity-seed
          projected:
            sources:
            - configMap:
                name: {{ include "vm-api.fullname" . }}-seed
            - configMap:
                name: {{ .Values.identity.identityMap }}
                items:
                  - key: seed.sh
                    path: seed.sh
                    mode: 0777
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
