apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vm-api.fullname" . }}
  labels:
    {{- include "vm-api.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "vm-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "vm-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vm-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          envFrom:
            - secretRef:
                name: {{ include "vm-api.fullname" . }}
          {{- if .Values.existingSecret }}
            - secretRef:
                name: {{ (tpl .Values.existingSecret .) }}
          {{- end }}
          {{- if .Values.certificateMap }}
          env:
            - name: SSL_CERT_DIR
              value: /usr/local/share/ca-certificates/
          {{- end }}
          command: {{- toYaml .Values.command | nindent 10 }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ default 8080 .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health/live
              port: http
          readinessProbe:
            httpGet:
              path: /api/health/ready
              port: http
          startupProbe:
            httpGet:
              path: /api/health/live
              port: http
            failureThreshold: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{ if .Values.certificateMap }}
            - mountPath: /usr/local/share/ca-certificates
              name: certificates
          {{- end }}
          {{ if .Values.iso.enabled }}
            - name: {{ include "vm-api.fullname" . }}-iso
              mountPath: /app/isos/player
          {{- end }}

      volumes:
      {{ if .Values.certificateMap }}
        - name: certificates
          configMap:
            name: {{ .Values.certificateMap }}
      {{- end }}
      {{ if .Values.iso.enabled }}
        - name: {{ include "vm-api.fullname" . }}-iso
          persistentVolumeClaim:
            claimName: {{ include "vm-api.fullname" . }}-iso
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
