apiVersion: v1
kind: Service
metadata:
  name: {{ include "vm-api.fullname" . }}
  labels:
    {{- include "vm-api.labels" . | nindent 4 }}
spec:
  type: {{ default "ClusterIP" .Values.service.type }}
  ports:
    - port: {{ default 80 .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vm-api.selectorLabels" . | nindent 4 }}
