apiVersion: v1
stringData:
  rabbitmq-password: crucible
  rabbitmq-erlang-cookie: 8MrqQdCQ6AQ8U3MacSubHE5RqkSfvNaRHzvxuFcG
kind: Secret
metadata:
  name: test-rabbitmq-secret
  namespace: imcite
type: Opaque
