apiVersion: v1
kind: Secret
metadata:
  name: test-stackstorm-config-secret
  namespace: imcite
type: Opaque
stringData:
  st2.secrets.conf: |
    [api]
    allow_origin = 'https://stackstorm.example.com'
    [database]
    host = stackstorm-mongodb.imcite.svc.cluster.local
    port = 27017
    db_name = st2
    username = administrator
    password = crucible
    [coordination]
    url = redis://redis:6379
    [messaging]
    url = amqp://administrator:crucible@stackstorm-rabbitmq.imcite.svc.cluster.local:5672/
    
