---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "player-ui.fullname" . }}
data:
  settings.env.json: |-
{{ if .Values.settingsYaml }}
{{- $settingsString := toYaml .Values.settingsYaml }}
{{- (tpl $settingsString .) | fromYaml | toPrettyJson | indent 4 }}
{{- else }}
{{- (tpl .Values.settings .) | indent 4 }}
{{- end }}
