apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix
  labels:
    service: postfix
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      service: postfix
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        service: postfix
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - env:
        securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: postfix
        ports:
        - containerPort: 25
          name: smtp
        - containerPort: 587
          name: submission
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - mountPath: /etc/postfix/maps/
          name: postfix
          subPath: postfix-conf/maps/
        - mountPath: /etc/postfix/main.cf
          name: postfix
          subPath: postfix-conf/main.cf
        - mountPath: /etc/postfix/master.cf
          name: postfix
          subPath: postfix-conf/master.cf
      restartPolicy: Always
      volumes:
      {{- range .Values.volumes }}
      - name: {{ .name }}
        persistentVolumeClaim:
          claimName: {{ .persistentVolumeClaim.claimName }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}