apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mattermost-team-edition.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mattermost-team-edition.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "mattermost-team-edition.chart" . }}
spec:
  replicas: 1
  strategy:
    type: Recreate
    rollingUpdate: null
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mattermost-team-edition.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret-config.yaml") . | sha256sum }}
        {{- if .Values.extraPodAnnotations }}
        {{- .Values.extraPodAnnotations | toYaml | nindent 8 }}
        {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "mattermost-team-edition.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ include "mattermost-team-edition.chart" . }}
    spec:
      initContainers:
      {{- if not .Values.externalDB.enabled }}
      - name: "init-mysql"
        image: "{{ .Values.initContainerImage.repository }}:{{ .Values.initContainerImage.tag }}"
        imagePullPolicy: {{ .Values.initContainerImage.imagePullPolicy }}
        command: ["sh", "-c", "until curl --max-time 10 http://{{ .Release.Name }}-mysql:3306; do echo waiting for {{ .Release.Name }}-mysql; sleep 5; done;"]
      {{- end }}
      {{ if .Values.persistence.config.enabled }}
      - name: "init-config"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        command: ["sh", "-c", "if [ ! -e config/config.json ]; then cp config.json config/; fi"]
        volumeMounts:
        - mountPath: /mattermost/config.json
          name: config-json
          subPath: config.json
        - mountPath: /mattermost/config
          name: mattermost-data
          subPath: {{ include "mattermost-team-edition.fullname" . }}/config
      {{- end }}
      {{- if .Values.extraInitContainers }}
      {{- .Values.extraInitContainers | toYaml | nindent 6 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        {{- if .Values.entryscript }}
        command: [ "/mattermost/bin/mattermost-custom-start" ]
        {{- end }}
        env:
        {{- if .Values.extraEnvVars }}
          {{- .Values.extraEnvVars | toYaml | nindent 10 }}
        {{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.service.internalPort }}
          protocol: TCP
        livenessProbe:
          initialDelaySeconds: 90
          timeoutSeconds: 5
          periodSeconds: 15
          httpGet:
            path: /api/v4/system/ping
            port: http
        readinessProbe:
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 15
          httpGet:
            path: /api/v4/system/ping
            port: http
        volumeMounts:
        - mountPath: /mattermost/bin/mattermost-custom-start
          name: config-entry
          subPath: entryscript
        {{ if .Values.persistence.config.enabled }}
        - mountPath: /mattermost/config
          name: mattermost-data
          subPath: {{ include "mattermost-team-edition.fullname" . }}/config
        {{- else }}
         - mountPath: /mattermost/config/config.json
          name: config-json
          subPath: config.json
        {{- end }}
        - mountPath: /mattermost/data
          name: mattermost-data
          subPath: {{ include "mattermost-team-edition.fullname" . }}/data
        - mountPath: /mattermost/{{ trimPrefix "./" .Values.configJSON.PluginSettings.Directory }}
          name: mattermost-data
          subPath: {{ include "mattermost-team-edition.fullname" . }}/plugins
        {{- if .Values.extraVolumeMounts -}}
        {{ .Values.extraVolumeMounts | toYaml | nindent 8 }}
        {{- end }}
        resources:
          {{- .Values.resources | toYaml | nindent 10 }}
      volumes:
      {{- if .Values.extraVolumes -}}
      {{ .Values.extraVolumes | toYaml | nindent 6 }}
      {{- end }}
      - name: config-entry
        configMap:
          name: {{ include "mattermost-team-edition.fullname" . }}-entry
          defaultMode: 511
      - name: config-json
        secret:
          secretName: {{ include "mattermost-team-edition.fullname" . }}-config-json
      - name: mattermost-data
      {{ if .Values.persistence.data.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.data.existingClaim | default (include "mattermost-team-edition.fullname" .) }}
      {{ else }}
        emptyDir: {}
      {{ end }}
      - name: mattermost-plugins
      {{ if .Values.persistence.plugins.enabled }}
        persistentVolumeClaim:
          {{ if .Values.persistence.plugins.existingClaim }}
          claimName: {{.Values.persistence.plugins.existingClaim }}
          {{ else }}
          claimName: {{ default (include "mattermost-team-edition.fullname" .) }}-plugins
          {{ end }}
      {{ else }}
        emptyDir: {}
      {{ end }}
      - name: mattermost-config
      {{ if .Values.persistence.config.enabled }}
        persistentVolumeClaim:
          {{ if .Values.persistence.config.existingClaim }}
          claimName: {{.Values.persistence.config.existingClaim }}
          {{ else }}
          claimName: {{ default (include "mattermost-team-edition.fullname" .) }}-config
          {{ end }}
      {{ else }}
        emptyDir: {}
      {{ end }}
