{{- $moodle := .Values.moodle | default dict }}
{{- $redis := $moodle.redis | default dict }}
{{- if and $redis.host $redis.password (not $redis.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-redis" (include "moodle.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "moodle.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- include "moodle.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ $redis.existingSecretKey | default "redis-password" }}: {{ $redis.password | quote }}
{{- end }}
