{{- $moodle := .Values.moodle | default dict }}
{{- if $moodle.config }}
{{- $split := fromYaml (include "moodle.config.split" $) }}
{{- if $split.plain }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "moodle.settings.secretName" . }}
  labels:
    {{- include "moodle.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- include "moodle.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  config.json: {{ toJson $split.plain | quote }}
{{- end }}
{{- end }}
