apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "foundry-buckets-api.fullname" . }}
  labels:
    {{- include "foundry-buckets-api.labels" . | nindent 4 }}

{{- if .Values.files }}
data:
{{- range $key, $val := .Values.files }}
  {{ $key }}: |
{{ $val  | indent 4}}
{{- end }}
{{- end }}

{{- if .Values.binaryFiles }}
binaryData:
{{- range $key, $val := .Values.binaryFiles }}
  {{ $key }}: |
{{ $val | indent 4}}
{{- end }}
{{- end }}
