apiVersion: v2
name: fite
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.0.0

dependencies:
- name: fite-api
  version: "0.1.0"
  repository: https://helm.cyberforce.site/charts
- name: fite-ui
  version: "0.1.0"
  repository: https://helm.cyberforce.site/charts