apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cubespace-server.fullname" . }}
  labels:
    {{- include "cubespace-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cubespace-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cubespace-server.selectorLabels" . | nindent 8 }}
    spec:
      hostname: {{ .Release.Name }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cubespace-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "./StandaloneLinux64"
            {{- if .Values.settings -}}
            {{- if .Values.settings.identityUri }}
            - "-identityURI"
            - "{{ .Values.settings.identityUri }}"
            {{- end }}
            {{- if .Values.settings.gamebrainUri }}
            - "-gamebrainURI"
            - "{{ .Values.settings.gamebrainUri }}"
            {{- end }}
            {{- if .Values.settings.uriBase }}
            - "-uriBase"
            - "{{ .Values.settings.uriBase }}"
            {{- end }}
            {{- if .Values.settings.clientID }}
            - "-clientID"
            - "{{ .Values.settings.clientID }}"
            {{- end }}
            {{- if .Values.settings.clientSecret }}
            - "-clientSecret"
            - "{{ .Values.settings.clientSecret }}"
            {{- end }}
            {{- if .Values.settings.debug }}
            - "-debug"
            {{- end }}
            {{- if .Values.settings.dev }}
            - "-dev"
            {{- end }}
            {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
