name: Release Charts

on:
  push:
    branches:
      - main

# The action needs to push to gh-pages and create GitHub Releases.
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          # chart-releaser requires full history to detect version changes
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v5
        with:
          version: "latest"

      - name: Add dependency Helm repos
        run: |
          helm repo add sei https://helm.cmusei.dev/charts
          helm repo add kvaps https://kvaps.github.io/charts
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo add runix https://helm.runix.net
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add cloudnative-pg https://cloudnative-pg.github.io/charts
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
